//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedidos
    {
        public int id_pedido { get; set; }
        public string nombre_recibe { get; set; }
        public string observacion_pedido { get; set; }
        public string observacion_producto { get; set; }
        public int total_productos { get; set; }
        public double valor_total { get; set; }
        public Nullable<int> id_producto { get; set; }
        public Nullable<int> id_cliente { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
